name: Build Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_REGISTRY_PASSWORD }}
      
    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: thetkpark/OnlineJudge
        tags: |
          type=raw,value=latest
          type=sha,format=long,prefix=
          
    - name: Build and push Docker image
      id: build-and-push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
